name: 'Copy to another repository'
description: 'Used for pushing a copy of a file or directory to another repository'
inputs:
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  source_target:
    description: 'Source file from the origin directory'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_branch:
    description: 'branch to push file to, defaults to main'
    required: false
  destination_folder:
    description: 'Directory to push the file to'
    required: false
  use_rsync:
    description: 'Copy files/directories using rsync instead of cp. Experimental feature, please know your use case'
    required: false
  commit_message:
    description: 'A custom message for the commit'
    required: false
  git_server:
    description: 'Git server host, default github.com'
    required: false
    default: github.com
  repo_level_secret:
    description: 'GitHub secret passed through calling Action'
    required: false
    default: 'not found'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.source-target }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.destination-branch }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.use-rsync }}
    - ${{ inputs.commit-message }}
    - ${{ inputs.git-server }}
    - ${{ inputs.repo-level-secret }}
branding:
  icon: 'git-commit'
  color: 'green'
