name: Deploy to release branch

env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  # Triggers the workflow on push or pull request events but only for dev branch
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false